s = set()
n = input("Enetr Number : ")
s.add(int(n))
n = input("Enetr Number : ")
s.add(int(n))
n = input("Enetr Number : ")
s.add(int(n))
n = input("Enetr Number : ")
s.add(int(n))
n = input("Enetr Number : ")
s.add(int(n))
n = input("Enetr Number : ")
s.add(int(n))
n = input("Enetr Number : ")
s.add(int(n))
n = input("Enetr Number : ")
s.add(int(n))
print(s)